name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        architecture: [x64, x86, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET Framework 4.8
      if: startsWith(matrix.os, 'windows')
      run: |
        # Установите .NET Framework 4.8 вручную

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      if: startsWith(matrix.os, 'windows')
      run: msbuild /t:restore /p:Configuration=Release
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
      run: msbuild /t:restore /p:Configuration=Release /usr/share/dotnet/sdk/4.8.1/

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: bin/Release
