name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        architecture: [x64, x86, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET Framework 4.8
      run: |
        choco install dotnet4.8 --yes --no-progress

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: msbuild /t:restore /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: bin/Release
